export const PRODUCT_LIST_PROCESS = 'PRODUCT_LIST_PROCESS'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_PROCESS = 'PRODUCT_DETAILS_PROCESS'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_BIDDER_REQUEST = 'PRODUCT_CREATE_BIDDER_REQUEST'
export const PRODUCT_CREATE_BIDDER_SUCCESS = 'PRODUCT_CREATE_BIDDER_SUCCESS'
export const PRODUCT_CREATE_BIDDER_FAIL = 'PRODUCT_CREATE_BIDDER_FAIL'
export const PRODUCT_CREATE_BIDDER_RESET = 'PRODUCT_CREATE_BIDDER_RESET'

export const PRODUCT_BIDDERS_REQUEST = 'PRODUCT_BIDDERS_REQUEST'
export const PRODUCT_BIDDERS_SUCCESS = 'PRODUCT_BIDDERS_SUCCESS'
export const PRODUCT_BIDDERS_FAIL = 'PRODUCT_BIDDERS_FAIL'
export const PRODUCT_BIDDERS_RESET = 'PRODUCT_BIDDERS_RESET'

export const PRODUCT_BIDDER_UPDATE_WIN_REQUEST =
  'PRODUCT_BIDDER_UPDATE_WIN_REQUEST'
export const PRODUCT_BIDDER_UPDATE_WIN_SUCCESS =
  'PRODUCT_BIDDER_UPDATE_WIN_SUCCESS'
export const PRODUCT_BIDDER_UPDATE_WIN_FAIL = 'PRODUCT_BIDDER_UPDATE_WIN_FAIL'
export const PRODUCT_BIDDER_UPDATE_WIN_RESET = 'PRODUCT_BIDDER_UPDATE_WIN_RESET'
